# Generated by Django 3.2.10 on 2021-12-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.TextField(default='Empty Name', max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='No Description', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=255, verbose_name='Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.group')),
            ],
        ),
    ]
