# Generated by Django 3.2.10 on 2021-12-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_Task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
